# 프로젝트의 디렉토리 구조와 각 부분의 역할을 정의합니다.
# AI는 이 파일을 참고하여 프로젝트의 전반적인 아키텍처와 파일 구성을 이해하고,
# 일관된 패턴으로 파일을 관리하며, 새로운 파일을 생성하거나 기존 파일의 위치를 결정할 때 활용합니다.

[project]
name = ""
description = ""
root_directory = "."

[directories]
vibe_workflow = { path = "vibe-workflow/", description = "LLM 규약 및 문서 파일들을 포함하는 디렉토리" }
language_framework_guidelines = { path = "vibe-workflow/language_framework_guidelines/", description = "특정 언어 및 프레임워크 사용 시 주의사항을 포함하는 디렉토리" }

[root_files]
clinerules = { path = ".clinerules", description = "AI 행동 원칙을 정의하는 루트 규칙 파일" }

[vibe_workflow_files]
readme = { path = "vibe-workflow/README.md", description = "LLM 이용 방법에 대한 가이드를 제공하는 파일" }
meeting_notes = { path = "vibe-workflow/meeting_notes.toml", description = "사용자와의 대화에서 도출된 주요 결정 사항, 새로운 아이디어, 변경된 맥락 등을 기록하는 파일" }
requirements_definition = { path = "vibe-workflow/requirements_definition.md", description = "프로젝트의 전체적인 요구사항을 정의하는 파일" }
feature_specification = { path = "vibe-workflow/feature_specification.md", description = "개별 기능의 상세 명세를 정의하는 파일" }
api_specification = { path = "vibe-workflow/api_specification.yaml", description = "API 명세를 정의하고 최신 상태를 유지하는 파일" }
database_schema = { path = "vibe-workflow/database_schema.dbml", description = "데이터베이스 스키마를 DBML 형식으로 정의하며, LLM이 데이터베이스 구조를 이해하는 데 참고하는 파일" }
ui_guidelines = { path = "vibe-workflow/ui_guidelines.md", description = "UI/UX 디자인 원칙 및 가이드라인을 정의하는 파일" }
coding_conventions = { path = "vibe-workflow/coding_conventions.md", description = "코딩 표준 및 컨벤션을 정의하고 관리하는 파일" }
configuration_guide = { path = "vibe-workflow/configuration_guide.md", description = "프로젝트 설정 방법 및 환경 변수 상세 안내를 제공하는 파일" }
test_case_template = { path = "vibe-workflow/test_case_template.md", description = "테스트 케이스 작성 표준 및 템플릿을 제공하는 파일" }

[language_framework_guidelines_files]
sveltekit_guidelines = { path = "vibe-workflow/language_framework_guidelines/sveltekit_guidelines.md", description = "SvelteKit 및 Svelte 5 사용 시 주의사항 및 가이드라인" }
hono_guidelines = { path = "vibe-workflow/language_framework_guidelines/hono_guidelines.md", description = "Hono 사용 시 주의사항 및 가이드라인" }
typescript_guidelines = { path = "vibe-workflow/language_framework_guidelines/typescript_guidelines.md", description = "TypeScript 사용 시 주의사항 및 가이드라인" }
html_guidelines = { path = "vibe-workflow/language_framework_guidelines/html_guidelines.md", description = "HTML 사용 시 주의사항 및 가이드라인" }
css_guidelines = { path = "vibe-workflow/language_framework_guidelines/css_guidelines.md", description = "CSS 사용 시 주의사항 및 가이드라인" }
tauri_guidelines = { path = "vibe-workflow/language_framework_guidelines/tauri_guidelines.md", description = "Tauri 사용 시 주의사항 및 가이드라인" }
