group_id = "frontend-screens"
title = "프론트엔드 화면 설계"
description = "프론트엔드 화면 구성 및 사용자 경험에 대한 질문 목록입니다. AI 추천을 선택시 'project-docs' 폴더의 관련 문서, 'project-definition.toml', 'tech-stack-questions.toml', 'api-design-questions.toml' 파일을 참조합니다."
current_question_id = ""

[[questions]]
id = "main-screens"
type = "choice"
prompt = "프로젝트에 필요한 주요 화면 목록을 정의해주세요. (예: 로그인, 회원가입, 대시보드, 상세 페이지 등)"
description = "서비스의 핵심 흐름을 구성하는 주요 화면들을 나열합니다."
options = ["🤖 AI 추천 (프로젝트 정의 기반 화면 제안)", "기타: _____"]

[[questions]]
id = "screen-purpose-function"
type = "choice"
prompt = "각 화면의 주요 목적과 제공할 핵심 기능은 무엇인가요?"
description = "각 화면이 사용자에게 제공하는 가치와 수행하는 기능을 구체적으로 설명합니다."
options = ["🤖 AI 추천 (화면 목록 기반 목적/기능 제안)", "기타: _____"]

[[questions]]
id = "key-ui-elements"
type = "choice"
prompt = "각 화면에 포함될 주요 UI 요소(버튼, 입력 필드, 목록, 차트 등)를 설명해주세요."
description = "화면별 핵심 인터페이스 구성 요소를 정의합니다."
options = ["🤖 AI 추천 (화면 기능 기반 UI 요소 제안)", "기타: _____"]

[[questions]]
id = "screen-flow"
type = "choice"
prompt = "사용자가 화면 간에 어떻게 이동하고 상호작용할지 주요 흐름(User Flow)을 설명해주세요."
description = "사용자 여정의 시작부터 끝까지 화면 전환 및 상호작용 시나리오를 정의합니다."
options = ["🤖 AI 추천 (주요 기능 기반 사용자 흐름 제안)", "기타: _____"]

[[questions]]
id = "responsive-accessibility"
type = "choice"
prompt = "다양한 기기(모바일, 태블릿, 데스크탑)에서의 반응형 디자인과 웹 접근성(WCAG)을 어떻게 고려할까요?"
description = "반응형 디자인 전략 및 웹 접근성 표준 준수 방안을 정의합니다."
options = ["🤖 AI 추천 (일반적인 반응형/접근성 모범 사례 제안)", "기타: _____"]

[[questions]]
id = "design-system-style-guide"
type = "choice"
prompt = "디자인 일관성을 위해 디자인 시스템 또는 스타일 가이드를 도입할 계획이 있나요?"
description = "디자인 시스템 또는 스타일 가이드 도입 여부 및 그 범위를 정의합니다."
options = ["🤖 AI 추천 (프로젝트 규모/복잡도 기반 제안)", "사용 안함", "기타: _____"]
