# questions/language.toml

group_id = "language-preferences"
title = "언어 설정"
description = "대화·문서·주석 언어에 대한 선호를 묻습니다."

[[questions]]
id = "interaction-language"
prompt = "안녕하세요! 앞으로 저와 어떤 언어로 대화하고 싶으신가요? (예: 한국어, 영어)"
description = "LLM과의 주된 소통에 사용될 언어입니다."

[[questions]]
id = "documentation-language"
prompt = "프로젝트 관련 문서나 기록은 어떤 언어로 남기는 것을 선호하시나요? (예: 한국어, 영어)"
description = "README, 커밋 메시지, 위키 등 공식 문서에 사용될 언어입니다."

[[questions]]
id = "comment-language"
prompt = "코드 내 주석은 주로 어떤 언어를 사용하실 예정인가요? (예: 영어, 한국어)"
description = "소스 코드 내부에 작성될 주석의 기본 언어입니다."
