# questions/project-definition.toml

group_id = "project-definition"
title = "프로젝트 정의"
description = "프로젝트의 핵심 기획 내용을 정의하는 질문 모음입니다."
# current_question_id: 현재 진행 중인 질문 ID.
# 첫 질문 전: ""
# 모든 질문 완료 후: "completed"
current_question_id = ""

[[questions]]
id = "service-definition"
prompt = "서비스 이름과 한 줄 설명(엘리베이터 피치)을 포함하여 서비스 개요를 정의해주세요."
description = "서비스 이름, 엘리베이터 피치, 해결하려는 문제, 제안하는 솔루션, 시장 타이밍 등을 포함합니다."

[[questions]]
id = "target-users"
prompt = "주요 타겟 사용자는 누구이며, 그들의 특징(페르소나)과 주요 니즈/문제, 사용 시나리오를 설명해주세요."
description = "프로젝트의 핵심 사용자를 구체적으로 정의합니다."

[[questions]]
id = "core-features"
prompt = "MVP에 반드시 포함되어야 할 핵심 기능 목록과 우선순위를 정의해주세요."
description = "필수 기능(Must-have)과 추가 기능(Should-have/Could-have) 목록 및 우선순위를 포함합니다."

[[questions]]
id = "technical-considerations"
prompt = "프로젝트 구현 시 중요하게 고려해야 할 기술적 요구사항(성능, 보안, 확장성 등)을 설명해주세요."
description = "프론트엔드, 백엔드 요구사항 및 예상 트래픽 규모 등을 포함합니다."

[[questions]]
id = "competitor-analysis"
prompt = "주요 경쟁 서비스는 무엇이며, 우리 서비스의 차별화 포인트는 무엇인가요?"
description = "주요 경쟁 서비스 분석 및 우리 서비스의 강점을 정의합니다."

[[questions]]
id = "mvp-scope"
prompt = "MVP의 최종 범위와 목표는 무엇이며, 이를 통해 무엇을 검증하고자 하시나요?"
description = "MVP에 포함될 기능 확정, 예상 일정, 검증할 핵심 가설을 정의합니다."

[[questions]]
id = "additional-considerations"
prompt = "수익 모델, 법적 이슈, 장기 로드맵 등 추가로 고려할 사항이 있다면 설명해주세요."
description = "프로젝트의 지속 가능성 및 확장성을 위한 추가 고려사항을 정의합니다."

[[questions]]
id = "supporting-documents"
prompt = "프로젝트 관련 사업 계획서, 보고서 등 참고 자료가 있다면 'project-docs' 폴더에 저장하여 관리하는 것을 권장합니다."
description = "'project-docs' 폴더에 프로젝트 정의와 관련된 외부 문서를 저장합니다."
options = ["네, 'project-docs' 폴더에 자료를 저장했습니다."]
