# questions/repository-type-and-links.toml

# 이 파일은 현재 리포지토리의 성격(백엔드/프론트엔드)을 파악하고,
# 필요한 경우 연관된 다른 리포지토리의 소스코드 주소를 수집하기 위한 질문을 정의합니다.

[[questions]]
id = "repository_type"
question = "현재 작업 중인 리포지토리는 백엔드입니까, 아니면 프론트엔드입니까?"
type = "choice"
options = ["백엔드", "프론트엔드"]
required = true

[[questions]]
id = "frontend_repo_url"
question = "현재 리포지토리가 백엔드라면, 프론트엔드 리포지토리의 소스코드 주소를 입력해주세요 (예: https://github.com/user/frontend-repo):"
type = "text"
required = false
# 'repository_type'이 '백엔드'일 때만 이 질문을 표시합니다.
condition = { field = "repository_type", value = "백엔드" }

[[questions]]
id = "backend_repo_url"
question = "현재 리포지토리가 프론트엔드라면, 백엔드 리포지토리의 소스코드 주소를 입력해주세요 (예: https://github.com/user/backend-repo):"
type = "text"
required = false
# 'repository_type'이 '프론트엔드'일 때만 이 질문을 표시합니다.
condition = { field = "repository_type", value = "프론트엔드" }
