group_id = "tech-stack"
title = "기술 스택 선정"
description = "프로젝트에 적용할 주요 기술 영역과 선택지를 정리한 질문 목록입니다. AI 추천을 선택시 'project-docs' 폴더의 관련 문서와 'project-definition.toml' 파일을 참조합니다."
current_question_id = ""

[[questions]]
id = "database"
type = "choice"
prompt = "주로 다룰 데이터의 종류와 구조는 무엇인가요?\n예상 데이터량, 읽기·쓰기 성능, 확장성 중 어떤 요소가 더 중요한가요?\n관계형(SQL)과 비관계형(NoSQL) 중 어떤 특성이 필요합니까?"
description = "데이터의 종류, 예상 데이터량, 성능 요구사항, 확장성, 그리고 관계형/비관계형 데이터베이스 특성 중 필요한 것을 정의합니다."
options = [
  "🤖 AI 추천 (요구사항 분석 후 추천)",
  "사용 안함 (정적 콘텐츠)",
  "간편 BaaS: Supabase, Firebase, Appwrite, PocketBase",
  "SQL: PostgreSQL, MariaDB, SQLite, AWS Aurora, CockroachDB, TiDB",
  "NoSQL: MongoDB, DynamoDB, Couchbase, Cosmos DB, Firestore",
  "인메모리/캐시: Redis, Memcached",
  "그래프 DB: Neo4j, Amazon Neptune",
  "기타: _____",
]

[[questions]]
id = "backend-framework"
type = "choice"
prompt = "선호 언어와 개발 생산성·성능·커뮤니티 지원 중 우선순위는 무엇인가요?\n서비스 복잡도에 따라 마이크로서비스 아키텍처를 고려하나요?"
description = "백엔드 개발 언어 선호도, 개발 생산성, 성능, 커뮤니티 지원 우선순위, 그리고 마이크로서비스 아키텍처 고려 여부를 정의합니다."
options = [
  "🤖 AI 추천 (서비스 특성 기반 추천)",
  "사용 안함 (프론트엔드 직접 BaaS 호출)",
  "Python: FastAPI",
  "JS/TS: Hono, Fastify, ElysiaJS, NestJS",
  "Rust: Actix-Web",
  "Go: Fiber",
  "기타: _____",
]

[[questions]]
id = "runtime-environment-js-ts-backend"
type = "choice"
prompt = "Node.js, Deno, Bun 중 어떤 런타임을 선호하시나요?\n패키지 호환성, 성능, 안정성 측면에서 고려할 점은?"
description = "JS/TS 백엔드 런타임(Node.js, Deno, Bun) 선호도, 패키지 호환성, 성능, 안정성 측면의 고려사항을 정의합니다."
options = ["🤖 AI 추천 (프레임워크 호환성 기반 추천)", "Node.js", "Deno", "Bun", "기타: _____"]

[[questions]]
id = "inter-service-communication"
type = "choice"
prompt = "내부 마이크로서비스 또는 외부 API와 어떤 방식으로 통신할 계획인가요?\n단순 요청·응답, 실시간 스트리밍, 메시지 큐 등이 필요합니까?"
description = "서비스 간 통신 방식(REST, GraphQL, gRPC, WebSocket 등) 및 데이터 포맷, 실시간 통신 필요 여부를 정의합니다."
options = [
  "🤖 AI 추천 (통신 패턴 기반 추천)",
  "사용 안함 (단일 서비스)",
  "REST / GraphQL / gRPC",
  "WebSocket / WebTransport / gRPC Streaming",
  "데이터 포맷: JSON, Protocol Buffers, Avro, MessagePack",
  "기타: _____",
]

[[questions]]
id = "api-gateway"
type = "choice"
prompt = "다수의 서비스 라우팅·인증·로깅·모니터링이 필요한가요?\n관리형 서비스와 자체 호스팅 중 선호 방식은 무엇인가요?"
description = "API 게이트웨이 필요 여부, 라우팅, 인증, 로깅, 모니터링 요구사항, 그리고 관리형/자체 호스팅 방식 선호도를 정의합니다."
options = [
  "🤖 AI 추천 (인프라 복잡도 기반 추천)",
  "사용 안함 (게이트웨이 불필요)",
  "관리형: AWS API Gateway, Apigee, Azure API Management",
  "오픈소스/자체 호스팅: Kong, Tyk, Envoy, Traefik, Nginx, KrakenD",
  "기타: _____",
]

[[questions]]
id = "graphql-gateway"
type = "choice"
prompt = "여러 GraphQL 스키마 통합·페더레이션·캐싱 기능이 필요한가요?"
description = "GraphQL 사용 시 GraphQL 스키마 통합, 페더레이션, 캐싱 기능 필요 여부를 정의합니다."
options = [
  "🤖 AI 추천 (GraphQL 아키텍처 기반 추천)",
  "사용 안함",
  "Apollo Gateway, GraphQL Mesh, Hasura(Remote Schemas), Mercurius, StepZen",
  "AWS AppSync",
  "기타: _____",
]

[[questions]]
id = "load-balancer"
type = "choice"
prompt = "트래픽 분산을 위한 로드 밸런싱이 필요한가요?\n클라우드 관리형 vs 소프트웨어 기반 중 어떤 방식을 선호하시나요?"
description = "트래픽 분산을 위한 로드 밸런싱 필요 여부, 그리고 클라우드 관리형/소프트웨어 기반 방식 선호도를 정의합니다."
options = [
  "🤖 AI 추천 (트래픽 패턴 기반 추천)",
  "사용 안함 (단일 서버)",
  "관리형: AWS ELB/ALB/NLB, Google Cloud LB, Azure LB",
  "소프트웨어: Nginx, HAProxy, Traefik",
  "기타: _____",
]

[[questions]]
id = "server-side-cache"
type = "choice"
prompt = "서비스 응답 속도 향상과 DB 부하 감소를 위해 캐시를 도입할 계획이신가요?\n어떤 데이터를 캐시하고, 캐시 일관성 수준은 어느 정도로 유지하시겠습니까?\n애플리케이션 캐시와 브라우저 캐시 중 무엇에 중점 두실 건가요?"
description = "서버 사이드 캐시 도입 계획, 캐시할 데이터 종류, 캐시 일관성 수준, 그리고 애플리케이션/브라우저 캐시 중 중점 사항을 정의합니다."
options = [
  "🤖 AI 추천 (캐시 전략 기반 추천)",
  "사용 안함",
  "인메모리 Key-Value: Redis, Memcached, Dragonfly, KeyDB",
  "분산 캐시: Hazelcast, etcd",
  "Java 기반: Ehcache",
  "관리형: AWS ElastiCache, Google Memorystore, Azure Cache",
  "기타: _____",
]

[[questions]]
id = "client-side-cache"
type = "choice"
prompt = "서비스 응답 속도 향상과 DB 부하 감소를 위해 캐시를 도입할 계획이신가요?\n어떤 데이터를 캐시하고, 캐시 일관성 수준은 어느 정도로 유지하시겠습니까?\n애플리케이션 캐시와 브라우저 캐시 중 무엇에 중점 두실 건가요?"
description = "클라이언트 사이드 캐시 도입 계획, 캐시할 데이터 종류, 캐시 일관성 수준, 그리고 애플리케이션/브라우저 캐시 중 중점 사항을 정의합니다."
options = [
  "🤖 AI 추천 (캐시 전략 기반 추천)",
  "사용 안함",
  "HTTP Caching: Cache-Control, ETag, Last-Modified",
  "Service Worker + Cache API",
  "localStorage / sessionStorage",
  "IndexedDB",
  "기타: _____",
]

[[questions]]
id = "cdn-waf"
type = "choice"
prompt = "전 세계 사용자에게 정적 콘텐츠를 빠르게 제공하고, 보안을 강화할 필요가 있나요?\n주요 대상 지역은 어디인가요?"
description = "CDN 및 WAF 필요 여부, 정적 콘텐츠 제공 및 보안 강화 요구사항, 그리고 주요 대상 지역을 정의합니다."
options = [
  "🤖 AI 추천 (지역·보안 요구 기반 추천)",
  "사용 안함",
  "통합: Cloudflare",
  "AWS: CloudFront + WAF",
  "GCP: Cloud CDN + Armor",
  "Azure: Front Door + WAF",
  "기타: _____",
]

[[questions]]
id = "frontend-graphics-game-engine"
type = "choice"
prompt = "UI 개발, 2D/3D 그래픽, 게임 엔진 중 어떤 기술이 필요하신가요?\n개발 생산성, 성능, 플랫폼 지원 중 우선순위는?"
description = "UI 개발, 2D/3D 그래픽, 게임 엔진 기술 필요 여부, 그리고 개발 생산성, 성능, 플랫폼 지원 우선순위를 정의합니다."
options = [
  "🤖 AI 추천 (프로젝트 요구 기반 추천)",
  "사용 안함",
  "웹 UI: Vanilla, SvelteKit, Astro, Next.js, Qwik, Remix, Nuxt, Fresh",
  "WebGL/3D: Three.js, Babylon.js, PixiJS, WebGPU",
  "게임 엔진: Unity, Unreal, Godot, Bevy",
  "기타: _____",
]

[[questions]]
id = "styling-tool"
type = "choice"
prompt = "CSS, 유틸리티-퍼스트, CSS-in-JS 중 어떤 스타일링 방식을 선호하시나요?\n디자인 시스템 통합이 필요한가요?"
description = "스타일링 방식(CSS, 유틸리티-퍼스트, CSS-in-JS) 선호도 및 디자인 시스템 통합 필요 여부를 정의합니다."
options = [
  "🤖 AI 추천 (디자인 요구 기반 추천)",
  "사용 안함",
  "Vanilla CSS / Modules",
  "유틸리티-퍼스트: Tailwind, UnoCSS",
  "CSS-in-JS: StyleX, Styled Components, Emotion",
  "기타: _____",
]

[[questions]]
id = "payment-processing"
type = "choice"
prompt = "결제 처리 기능이 필요한가요?"
description = "결제 처리 기능 필요 여부 및 선호하는 결제 서비스 제공업체를 정의합니다."
options = [
  "🤖 AI 추천 (시장·수수료 기반 추천)",
  "사용 안함",
  "Stripe, PayPal, Toss, Wise, Payoneer, KakaoPay, NaverPay",
  "기타: _____",
]

[[questions]]
id = "analytics-ab-testing"
type = "choice"
prompt = "분석 및 A/B 테스트 도구가 필요한가요?"
description = "사용자 행동 분석 및 A/B 테스트 도구 필요 여부를 정의합니다."
options = [
  "🤖 AI 추천 (데이터 프라이버시·분석 규모 기반 추천)",
  "사용 안함",
  "분석: Google Analytics, Plausible, PostHog",
  "A/B 테스트: GrowthBook, Flagsmith",
  "기타: _____",
]

[[questions]]
id = "seo-ssr"
type = "choice"
prompt = "SEO 및 SSR(서버 사이드 렌더링) 기능이 필요한가요?"
description = "SEO 및 SSR 기능 필요 여부를 정의합니다."
options = [
  "🤖 AI 추천 (SEO·렌더링 요구 기반 추천)",
  "사용 안함",
  "Prerender.io",
  "프레임워크 내 SSR/SSG 활용",
  "기타: _____",
]

[[questions]]
id = "container-deployment"
type = "choice"
prompt = "컨테이너화 및 배포 전략이 필요한가요?"
description = "컨테이너화 및 배포 전략 필요 여부, 그리고 선호하는 컨테이너/배포 플랫폼을 정의합니다."
options = [
  "🤖 AI 추천 (운영 복잡성·확장성 기반 추천)",
  "사용 안함",
  "Docker, Kubernetes",
  "Fly.io, AWS ECS/EKS/Fargate",
  "Vercel, Netlify, Render",
  "기타: _____",
]

[[questions]]
id = "ci-cd"
type = "choice"
prompt = "CI/CD(지속적 통합/지속적 배포) 파이프라인이 필요한가요?"
description = "CI/CD 파이프라인 필요 여부 및 선호하는 CI/CD 도구를 정의합니다."
options = [
  "🤖 AI 추천 (저장소·배포 환경 기반 추천)",
  "사용 안함",
  "GitHub Actions, GitLab CI, CircleCI",
  "Jenkins, Bitbucket Pipelines",
  "기타: _____",
]

[[questions]]
id = "test-automation"
type = "choice"
prompt = "테스트 자동화 도구가 필요한가요?"
description = "테스트 자동화 도구 필요 여부 및 선호하는 테스트 프레임워크를 정의합니다."
options = [
  "🤖 AI 추천 (테스트 유형 기반 추천)",
  "사용 안함",
  "Playwright, Vitest, k6, Newman",
  "기타: _____",
]

[[questions]]
id = "advertising-monetization"
type = "choice"
prompt = "광고 및 수익화 전략이 필요한가요?"
description = "광고 및 수익화 전략 필요 여부 및 선호하는 광고 플랫폼을 정의합니다."
options = [
  "🤖 AI 추천 (콘텐츠·타겟 기반 추천)",
  "사용 안함",
  "Google AdSense, Mediavine, Raptive, Ezoic, Monumetric",
  "기타: _____",
]

[[questions]]
id = "desktop-application-framework"
type = "choice"
prompt = "데스크탑 앱 개발 계획이 있으신가요? 지원 OS와 주요 요구사항은 무엇인가요?"
description = "데스크탑 앱 개발 계획 여부, 지원 OS, 그리고 주요 요구사항을 정의합니다."
options = [
  "🤖 AI 추천 (플랫폼·언어 기반 추천)",
  "사용 안함",
  "Tauri",
  "WinUI",
  "Qt",
  "Iced, Slint, egui (Rust)",
  "기타: _____",
]
