# questions/update-clinerules-auto.toml

# 이 파일은 LLM이 .clinerules 파일을 자동으로 업데이트하는 작업을 정의합니다.
# LLM은 이 파일을 참고하여 기존 .clinerules에 중요한 링크와 설명을 추가합니다.

group_id = "update-clinerules-auto"
title = ".clinerules 자동 업데이트"
description = "LLM이 기존 .clinerules 파일을 분석하고, 워크플로우 진행 중 수집된 정보(예: 리포지토리 유형, 관련 링크, 프로젝트 정의, 기술 스택 등)를 기반으로 LLM이 참고할 만한 중요한 링크와 설명을 추가합니다. 이 과정은 사용자에게 질문 없이 자동으로 진행됩니다."
current_question_id = ""

[[questions]]
id = "perform-update"
description = "LLM은 이 단계를 통해 .clinerules 파일을 직접 업데이트합니다. 이 작업은 사용자 입력 없이 자동으로 수행됩니다."
